name: Mike Chirico Action
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: dev-action action step
      id: dev-action
      uses: mchirico/dev-action@v1
      with:
        milliseconds: 1000
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: |
        echo "The time was ${{ steps.dev-action.outputs.time }}"
        echo "nameToGreet ${{ steps.dev-action.outputs.nameToGreet }}"
